### ISSUE TITLE
Updates needed for Todoist

### ISSUE THREAD

**Issue by odsamuels** [HeRoMo/gas-todoist#225]
Hi HeRoMo,

I'm the CX Developer at Todoist and am very happy to have discovered this integration.

I am noticing a few things in your repo that could use some updating and would like to be a contributor so that I can submit some Pull Requests.

Would that be something that you would be interested in?

**Comment by odsamuels** [comment]
I was able to propose my changes.

**Comment by HeRoMo** [comment]
Hi, odsamuels

I merged your PRs.
Thank you for your contribution.
